from datetime import UTC, datetime

import jinja2


class AssemblyEngine:
    """
    Merges per-part OpenSCAD source files into a single assembly file.
    Uses a Jinja2 template to keep the output structure consistent.
    """

    TEMPLATE = """\
// Generated by Gemini Vision Studio v3.0
// Job ID: {{ job_id }}
// Generated at: {{ timestamp }}

$fn = 64;

{% for part in parts %}
// === Part: {{ part.name }} (ID: {{ part.id }}) ===
{{ part.code }}

{% endfor %}

// === Assembly ===
module full_assembly() {
    {% for part in parts %}
    {{ part.name }}();
    {% endfor %}
}

full_assembly();
"""

    def build(self, parts: list[dict], job_id: str) -> str:
        template = jinja2.Template(self.TEMPLATE)
        return template.render(
            job_id=job_id,
            timestamp=datetime.now(UTC).isoformat(),
            parts=parts,
        )
